recipe: default.v1
language: ko
pipeline:
- name: SpacyNLP
  model: ko_core_news_sm
- name: custom.mecab_tokenizer.mecabtok_3.MecabTokenizer
  intent_tokenization_flag: false
  intent_split_symbol: _
  token_pattern: None
- name: custom.gloVe_featurizer.gloVe_feature.GloveFeaturizer
  alias: gloVe
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 50
- name: EntitySynonymMapper
policies:
- name: TEDPolicy
  epochs: 100
- name: AugmentedMemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
assistant_id: 20230505-034049-charcoal-bug
